/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CameraRouteImport } from './routes/camera'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CourseAlbumCourseIdRouteImport } from './routes/course-album.$courseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraRoute = CameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseAlbumCourseIdRoute = CourseAlbumCourseIdRouteImport.update({
  id: '/course-album/$courseId',
  path: '/course-album/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/camera': typeof CameraRoute
  '/courses': typeof CoursesRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/course-album/$courseId': typeof CourseAlbumCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/camera': typeof CameraRoute
  '/courses': typeof CoursesRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/course-album/$courseId': typeof CourseAlbumCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/camera': typeof CameraRoute
  '/courses': typeof CoursesRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/course-album/$courseId': typeof CourseAlbumCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/camera'
    | '/courses'
    | '/schedule'
    | '/settings'
    | '/course-album/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/camera'
    | '/courses'
    | '/schedule'
    | '/settings'
    | '/course-album/$courseId'
  id:
    | '__root__'
    | '/'
    | '/camera'
    | '/courses'
    | '/schedule'
    | '/settings'
    | '/course-album/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CameraRoute: typeof CameraRoute
  CoursesRoute: typeof CoursesRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  CourseAlbumCourseIdRoute: typeof CourseAlbumCourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera': {
      id: '/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof CameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-album/$courseId': {
      id: '/course-album/$courseId'
      path: '/course-album/$courseId'
      fullPath: '/course-album/$courseId'
      preLoaderRoute: typeof CourseAlbumCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CameraRoute: CameraRoute,
  CoursesRoute: CoursesRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  CourseAlbumCourseIdRoute: CourseAlbumCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
